# Generated By Claude 3.5 Sonnet

import random

def roll_die():
    return random.randint(1, 6)

def take_turn(player_name, current_score):
    turn_score = 0
    while True:
        choice = input(f"{player_name}, your score is {current_score}. Current turn: {turn_score}. Roll or hold? (r/h): ").lower()
        if choice == 'h':
            return turn_score
        elif choice == 'r':
            roll = roll_die()
            print(f"{player_name} rolled a {roll}")
            if roll == 1:
                print(f"{player_name} loses their turn!")
                return 0
            else:
                turn_score += roll
        else:
            print("Invalid choice. Please enter 'r' to roll or 'h' to hold.")

def play_pig_game():
    player1_score = 0
    player2_score = 0
    target_score = 100

    while player1_score < target_score and player2_score < target_score:
        print("\nCurrent scores:")
        print(f"Player 1: {player1_score}")
        print(f"Player 2: {player2_score}")

        player1_score += take_turn("Player 1", player1_score)
        if player1_score >= target_score:
            break

        player2_score += take_turn("Player 2", player2_score)

    if player1_score >= target_score:
        print("\nPlayer 1 wins!")
    else:
        print("\nPlayer 2 wins!")

    print(f"Final scores: Player 1: {player1_score}, Player 2: {player2_score}")

if __name__ == "__main__":
    print("Welcome to the Pig Dice Game!")
    print("First player to reach 100 points wins.")
    play_pig_game()